name: linki
description: A minimal RSS and bookmark app.
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  drift: ^2.28.0
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1
  url_launcher: ^6.3.2
  cupertino_icons: ^1.0.8
  xml: ^6.6.1
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  drift_dev: ^2.28.0
  build_runner: ^2.7.1
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFFFFF"  # optional: background color for Android adaptive icon
  adaptive_icon_foreground: "assets/images/app_icon.png"  # optional: foreground layer
  remove_alpha_ios: true  # iOS requires no transparency
